yolo_model:

  config_file:
    name: darknetyolo.cfg
  weight_file:
    name: darknet3800.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - Water dipper
      - Broom
      - Tiffin carrier
      - Sticky rice basket
      - Dish cover
      - Colander
      - Prickly heat powder
      - Fanning woven
      - Chamber pot
      - Back scratcher
